[versions]
# Versions set-up for gradle-plugins and required APIs and libraries.
shadow = "8.3.5"
spotless = "6.13.0"
indra = "3.1.3"
blossom = "2.1.0"

paper = "1.21.1-R0.1-SNAPSHOT"
worldguard = "7.0.12"
configurate = "4.1.2"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
worldguard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }
configurate = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
indra = { id = "net.kyori.indra", version.ref = "indra" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom"}
